services:
    # Manager
    whatwedo_crud.manager.definition:
        class: whatwedo\CrudBundle\Manager\DefinitionManager

    whatwedo_crud.manager.block:
        class: whatwedo\CrudBundle\Manager\BlockManager

    whatwedo_crud.manager.content:
        class: whatwedo\CrudBundle\Manager\ContentManager

    # Definition
    whatwedo_crud.definition.abstract_definition:
        abstract:  true
        calls:
            - [setBlockManager, ['@whatwedo_crud.manager.block']]
            - [setDoctrine, ['@doctrine']]
            - [setRequestStack, ['@request_stack']]
            - [setDefinitionView, ['@whatwedo_crud.view.definition_view']]
            - [setDefinitionManager, ['@whatwedo_crud.manager.definition']]

    # Block
    whatwedo_crud.block.block:
        class: whatwedo\CrudBundle\Block\Block
        tags:
            - crud.block
        calls:
            - [setContentManager, ['@whatwedo_crud.manager.content']]

    # Content
    whatwedo_crud.content.content:
        class: whatwedo\CrudBundle\Content\Content
        tags:
            - crud.content
        calls:

    whatwedo_crud.content.relation:
        class: whatwedo\CrudBundle\Content\RelationContent
        arguments:
            - '@service_container'
        tags:
            - crud.content

    whatwedo_crud.content.table:
        class: whatwedo\CrudBundle\Content\TableContent
        tags:
            - crud.content

    whatwedo_crud.content.twig:
        class: whatwedo\CrudBundle\Content\TwigContent
        tags:
            - crud.content

    # View
    whatwedo_crud.view.definition_view:
        class: whatwedo\CrudBundle\View\DefinitionView
        shared: false
        arguments:
            - '@templating'
            - '@form.factory'
            - '@router'
            - '@security.access_map'
            - '@security.authorization_checker'
        calls:
            - [setDefinitionManager, ['@whatwedo_crud.manager.definition']]

    # Route Loader
    whatwedo_crud.routing.crud_loader:
        class: whatwedo\CrudBundle\Routing\CrudLoader
        arguments:
            - '@whatwedo_crud.manager.definition'
        tags:
            - { name: routing.loader }

    # Event Listener
    whatwedo_crud.event_listener.crud_definition:
        class: whatwedo\CrudBundle\EventListener\CrudDefinitionListener
        arguments:
            - '@whatwedo_crud.manager.definition'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # Twig Extension
    whatwedo_crud.twig.callable_extension:
        class: whatwedo\CrudBundle\Twig\CallableExtension
        tags:
            - { name: twig.extension }

    # Extensions
    whatwedo_crud.extension.breadcrumbs:
        class: whatwedo\CrudBundle\Extension\BreadcrumbsExtension
        arguments:
            - '@white_october_breadcrumbs'
            - '%whatwedo_crud.config.breadcrumbs.home.text%'
            - '%whatwedo_crud.config.breadcrumbs.home.route%'
        tags:
            - { name: crud.extension, alias: breadcrumb }

    # Form types
    whatwedo_crud.type.entity_hidden:
       class: whatwedo\CrudBundle\Form\EntityHiddenType
       arguments: ["@doctrine.orm.entity_manager"]
       tags:
       - { name: form.type, alias: entity_hidden }

    whatwedo_crud.form_type.ajax_select:
        class: whatwedo\CrudBundle\Form\Type\AjaxSelectFormType
        arguments:
            - "@router"
        tags:
            - { name: form.type, alias: ajaxSelect }